# Generated by Django 5.2.17 on 2026-08-23 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('bank_transaction_id', models.CharField(help_text='e.g. btx_001', max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Bank statement description / UTR / Reference', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Net amount credited to bank', max_digits=14)),
                ('transaction_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(db_index=True, default='HDFC Bank', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-transaction_date', 'bank_transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(help_text='Internal ID e.g. P001', max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross customer payment amount', max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_date', models.DateField(db_index=True)),
                ('gateway', models.CharField(db_index=True, default='RAZORPAY', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'verbose_name_plural': 'Customer Payments',
                'ordering': ['-payment_date', 'payment_id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('matched_records', models.PositiveIntegerField(default=0)),
                ('resolved_records', models.PositiveIntegerField(default=0)),
                ('exception_records', models.PositiveIntegerField(default=0)),
                ('unresolved_records', models.PositiveIntegerField(default=0)),
                ('match_rate', models.FloatField(default=0.0, help_text='Percentage of auto-reconciled records')),
                ('accuracy', models.FloatField(default=0.0, help_text='Classification accuracy against ground truth')),
                ('avg_confidence', models.FloatField(default=0.0, help_text='Average agent confidence score (0-100)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Job',
                'verbose_name_plural': 'Reconciliation Jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('gateway_transaction_id', models.CharField(help_text='e.g. pay_gtw_001', max_length=64, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_on_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='CAPTURED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Mapped payment reference (can be null for rogue/orphaned gateway transactions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transactions', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Gateway Transaction',
                'verbose_name_plural': 'Gateway Transactions',
                'ordering': ['-settlement_date', 'gateway_transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('AMOUNT_MISMATCH', 'Amount Mismatch'), ('MISSING_BANK_TRANSACTION', 'Missing Bank Settlement'), ('MISSING_GATEWAY_RECORD', 'Missing Gateway Record'), ('DELAYED_SETTLEMENT', 'Delayed Settlement'), ('DUPLICATE_SETTLEMENT', 'Duplicate Settlement'), ('NAME_MISMATCH', 'Customer/Entity Name Variation'), ('UNEXPLAINED_FEE', 'Unexplained Bank/Gateway Deductions'), ('UNKNOWN', 'Unknown Exception')], db_index=True, max_length=50)),
                ('reason', models.TextField()),
                ('suggested_action', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Exception Record',
                'verbose_name_plural': 'Exception Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('agent_node', models.CharField(db_index=True, help_text='e.g. deterministic_match, gemini_investigate', max_length=100)),
                ('tool_called', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('tool_output', models.JSONField(blank=True, default=dict)),
                ('llm_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reconciliation_result', serialize=False, to='finance.payment')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MATCHED_DELAYED', 'Matched (Delayed Settlement)'), ('RESOLVED', 'Resolved by AI'), ('EXCEPTION', 'Exception Detected'), ('UNRESOLVED', 'Unresolved / Escalated to Human')], db_index=True, default='EXCEPTION', max_length=30)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence between 0.00 and 1.00')),
                ('reason', models.TextField(blank=True, null=True)),
                ('suggested_action', models.TextField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='List of verifiable facts found during audit')),
                ('llm_response', models.JSONField(blank=True, default=dict, help_text='Validated structured response from Gemini')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='finance.reconciliationjob')),
            ],
            options={
                'verbose_name': 'Reconciliation Result',
                'verbose_name_plural': 'Reconciliation Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
