# Generated by Django 5.2.17 on 2026-08-23 11:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruthRecord',
            fields=[
                ('payment_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('scenario_type', models.CharField(help_text='e.g. EXACT_MATCH, ENTITY_VARIATION, MISSING_BANK', max_length=64)),
                ('expected_status', models.CharField(choices=[('MATCHED', 'Matched'), ('MATCHED_DELAYED', 'Matched Delayed'), ('RESOLVED', 'Resolved'), ('EXCEPTION', 'Exception'), ('UNRESOLVED', 'Unresolved')], max_length=32)),
                ('expected_confidence', models.FloatField(default=0.95)),
                ('expected_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expected_reason', models.TextField()),
                ('is_resolvable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ground Truth Record',
                'verbose_name_plural': 'Ground Truth Records',
                'ordering': ['payment_id'],
            },
        ),
    ]
